version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: matchgame-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: matchgame
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
